title:              Tho Nguyen's Blog
email:              phuctho.contact@gmail.com
description:        A technical blog - Tips & Tricks
author:             Tho Nguyen
baseurl:            ""
url:                "https://thonguyen212210.github.io"

# Social Profiles   
github_username:    Thonguyen212210
facebook_username:  Thọ Nguyễn
instagram_username:  thonguyen2210.in
linkedin_username:  THO NGUYEN DUY PHUC

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
